language: d
sudo: false

matrix:
    include:
        - d: dmd-2.079.1
        - d: dmd-2.078.3
        - d: dmd-2.077.1
        - d: ldc-1.8.0
        - d: ldc-1.7.0
        - d: ldc-1.6.0

# Ddox dependencies
addons:
  apt:
    packages:
      - libevent-dev

script:
  - ./ci.sh
  # - dub build -b ddox

after_success:
 - bash <(curl -s https://codecov.io/bash)

# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: $TRAVIS_BUILD_DIR/docs
#   github_token: $GH_REPO_TOKEN
#   on:
#     branch: master
